# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160826_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
